#!/bin/bash
chmod -R 777 /opt/ros/hydro/stacks/qbo_webi/src/xmms2/songs/
chmod -R 777 /opt/ros/hydro/stacks/qbo_webi/src/recorder/videos/
chmod 666 /opt/ros/hydro/stacks/qbo_linphone/config/linphonerc.in 

export PYTHONPATH=/opt/ros/hydro/stacks/qbo_webi/src/teleoperation/sip2rtmp/p2p-sip:$PYTHONPATH


