@REM This batch file has been generated by the IAR Embedded Workbench
@REM C-SPY Debugger, as an aid to preparing a command line for running
@REM the cspybat command line utility using the appropriate settings.
@REM
@REM You can launch cspybat by typing the name of this batch file followed
@REM by the name of the debug file (usually an ELF/DWARF or UBROF file).
@REM Note that this file is generated every time a new debug session
@REM is initialized, so you may want to move or rename the file before
@REM making changes.
@REM 


"C:\Archivos de programa\IAR Systems\Embedded Workbench 6.0\common\bin\cspybat" "C:\Archivos de programa\IAR Systems\Embedded Workbench 6.0\arm\bin\armproc.dll" "C:\Archivos de programa\IAR Systems\Embedded Workbench 6.0\arm\bin\armrdi.dll"  %1 --plugin "C:\Archivos de programa\IAR Systems\Embedded Workbench 6.0\arm\bin\armbat.dll" --flash_loader "C:\Archivos de programa\IAR Systems\Embedded Workbench 6.0\arm\config\flashloader\ST\FlashSTM32F10xx6.board" --backend -B "--endian=little" "--cpu=Cortex-M3" "--fpu=None" "-p" "C:\Archivos de programa\IAR Systems\Embedded Workbench 6.0\arm\CONFIG\debugger\ST\iostm32f10xx4.ddf" "--semihosting" "--device=STM32F10xx6" "--rdi_driver_dll=C:\Archivos de programa\CooCox\CoIARPlugin\CoRDI.dll" "--drv_communication_log=C:\Archivos de programa\IAR Systems\Embedded Workbench 6.0\arm\cspycomm.log" "--drv_catch_exceptions=0x000" 


