#!/bin/bash
chmod 777 /opt/ros/electric/stacks/qbo_stack/qbo_face_vision/qbo_face_recognition/faces/new_faces
chmod 777 /opt/ros/electric/stacks/qbo_stack/qbo_face_vision/qbo_face_recognition/faces/faces_db
