"""autogenerated by genmsg_py from PlanarBaseVelLimits.msg. Do not edit."""
import roslib.message
import struct

import std_msgs.msg

class PlanarBaseVelLimits(roslib.message.Message):
  _md5sum = "79d6a8bc99f5988deabb3198a791ba92"
  _type = "hrl_lib/PlanarBaseVelLimits"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """# max allowable velocities in positive and negative X and Y directions
# and max allowable angular velocity.
Header header
float64 xvel_pos_max
float64 xvel_neg_max
float64 yvel_pos_max
float64 yvel_neg_max
float64 avel_max


================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

"""
  __slots__ = ['header','xvel_pos_max','xvel_neg_max','yvel_pos_max','yvel_neg_max','avel_max']
  _slot_types = ['Header','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       header,xvel_pos_max,xvel_neg_max,yvel_pos_max,yvel_neg_max,avel_max
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(PlanarBaseVelLimits, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg._Header.Header()
      if self.xvel_pos_max is None:
        self.xvel_pos_max = 0.
      if self.xvel_neg_max is None:
        self.xvel_neg_max = 0.
      if self.yvel_pos_max is None:
        self.yvel_pos_max = 0.
      if self.yvel_neg_max is None:
        self.yvel_neg_max = 0.
      if self.avel_max is None:
        self.avel_max = 0.
    else:
      self.header = std_msgs.msg._Header.Header()
      self.xvel_pos_max = 0.
      self.xvel_neg_max = 0.
      self.yvel_pos_max = 0.
      self.yvel_neg_max = 0.
      self.avel_max = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_5d.pack(_x.xvel_pos_max, _x.xvel_neg_max, _x.yvel_pos_max, _x.yvel_neg_max, _x.avel_max))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg._Header.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 40
      (_x.xvel_pos_max, _x.xvel_neg_max, _x.yvel_pos_max, _x.yvel_neg_max, _x.avel_max,) = _struct_5d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_5d.pack(_x.xvel_pos_max, _x.xvel_neg_max, _x.yvel_pos_max, _x.yvel_neg_max, _x.avel_max))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg._Header.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 40
      (_x.xvel_pos_max, _x.xvel_neg_max, _x.yvel_pos_max, _x.yvel_neg_max, _x.avel_max,) = _struct_5d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_5d = struct.Struct("<5d")
_struct_3I = struct.Struct("<3I")
