"""autogenerated by genmsg_py from VO_Data.msg. Do not edit."""
import roslib.message
import struct

import std_msgs.msg

class VO_Data(roslib.message.Message):
  _md5sum = "68f198b42a714abe05a8e1625896ffa1"
  _type = "hrl_lib/VO_Data"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header
float64[] x_error
float64[] y_error
float64[] x_feat_1
float64[] y_feat_1
float64[] x_feat_2
float64[] y_feat_2
float64 focal
float64 dt
float64 im_height
float64 im_width
float64 time



================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

"""
  __slots__ = ['header','x_error','y_error','x_feat_1','y_feat_1','x_feat_2','y_feat_2','focal','dt','im_height','im_width','time']
  _slot_types = ['Header','float64[]','float64[]','float64[]','float64[]','float64[]','float64[]','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       header,x_error,y_error,x_feat_1,y_feat_1,x_feat_2,y_feat_2,focal,dt,im_height,im_width,time
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(VO_Data, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg._Header.Header()
      if self.x_error is None:
        self.x_error = []
      if self.y_error is None:
        self.y_error = []
      if self.x_feat_1 is None:
        self.x_feat_1 = []
      if self.y_feat_1 is None:
        self.y_feat_1 = []
      if self.x_feat_2 is None:
        self.x_feat_2 = []
      if self.y_feat_2 is None:
        self.y_feat_2 = []
      if self.focal is None:
        self.focal = 0.
      if self.dt is None:
        self.dt = 0.
      if self.im_height is None:
        self.im_height = 0.
      if self.im_width is None:
        self.im_width = 0.
      if self.time is None:
        self.time = 0.
    else:
      self.header = std_msgs.msg._Header.Header()
      self.x_error = []
      self.y_error = []
      self.x_feat_1 = []
      self.y_feat_1 = []
      self.x_feat_2 = []
      self.y_feat_2 = []
      self.focal = 0.
      self.dt = 0.
      self.im_height = 0.
      self.im_width = 0.
      self.time = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      length = len(self.x_error)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.x_error))
      length = len(self.y_error)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.y_error))
      length = len(self.x_feat_1)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.x_feat_1))
      length = len(self.y_feat_1)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.y_feat_1))
      length = len(self.x_feat_2)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.x_feat_2))
      length = len(self.y_feat_2)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.y_feat_2))
      _x = self
      buff.write(_struct_5d.pack(_x.focal, _x.dt, _x.im_height, _x.im_width, _x.time))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg._Header.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.x_error = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.y_error = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.x_feat_1 = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.y_feat_1 = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.x_feat_2 = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.y_feat_2 = struct.unpack(pattern, str[start:end])
      _x = self
      start = end
      end += 40
      (_x.focal, _x.dt, _x.im_height, _x.im_width, _x.time,) = _struct_5d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      length = len(self.x_error)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.x_error.tostring())
      length = len(self.y_error)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.y_error.tostring())
      length = len(self.x_feat_1)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.x_feat_1.tostring())
      length = len(self.y_feat_1)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.y_feat_1.tostring())
      length = len(self.x_feat_2)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.x_feat_2.tostring())
      length = len(self.y_feat_2)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.y_feat_2.tostring())
      _x = self
      buff.write(_struct_5d.pack(_x.focal, _x.dt, _x.im_height, _x.im_width, _x.time))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg._Header.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.x_error = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.y_error = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.x_feat_1 = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.y_feat_1 = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.x_feat_2 = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.y_feat_2 = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      _x = self
      start = end
      end += 40
      (_x.focal, _x.dt, _x.im_height, _x.im_width, _x.time,) = _struct_5d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_5d = struct.Struct("<5d")
_struct_3I = struct.Struct("<3I")
